// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persion.proto

//指定包名

package pd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//标示位本
type Stu struct {
	//名字
	Score                int32    `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stu) Reset()         { *m = Stu{} }
func (m *Stu) String() string { return proto.CompactTextString(m) }
func (*Stu) ProtoMessage()    {}
func (*Stu) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7f5642358fd2963, []int{0}
}

func (m *Stu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stu.Unmarshal(m, b)
}
func (m *Stu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stu.Marshal(b, m, deterministic)
}
func (m *Stu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stu.Merge(m, src)
}
func (m *Stu) XXX_Size() int {
	return xxx_messageInfo_Stu.Size(m)
}
func (m *Stu) XXX_DiscardUnknown() {
	xxx_messageInfo_Stu.DiscardUnknown(m)
}

var xxx_messageInfo_Stu proto.InternalMessageInfo

func (m *Stu) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Stu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Stu)(nil), "pd.Stu")
}

func init() { proto.RegisterFile("persion.proto", fileDescriptor_a7f5642358fd2963) }

var fileDescriptor_a7f5642358fd2963 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0x2d, 0x2a,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x51, 0xd2, 0xe7,
	0x62, 0x0e, 0x2e, 0x29, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4e, 0xce, 0x2f, 0x4a, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98,
	0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0xec, 0x24, 0x36, 0xb0, 0x5e, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0x6a, 0x4c, 0x48, 0x4c, 0x00, 0x00, 0x00,
}
